### PR TITLE
Tawau

### PR DESCRIPTION
**Pull request by NistorCristian**
Hi,
I apologize again for my mistake in #4 . From now on I will put the themes one by one.

## Theme Submission checklist

- [x] Pull Request title is title of theme (and nothing else)
- [x] Code changes are a [properly formatted submission](https://github.com/TryGhost/Marketplace/blob/master/.github/CONTRIBUTING.md)
- [x] Theme passes [GScan](https://gscan.ghost.org/)
- [x] I have read about [how the marketplace works](https://github.com/TryGhost/Marketplace/blob/master/README.md) and I completely understand that not all themes are accepted.

### CODE REVIEW

**Comment by JohnONolan** [comment]
Would be happy to accept this submission but the screenshot is pixelated and covered in JPG artifacts. If you can update the PR with a suitable image then I'll merge it

**Comment by NistorCristian** [comment]
Updated. Instead of tinypng, that made the image pixelated, I lowered the quality from photoshop.

**Comment by NistorCristian** [comment]
I think I wrote something wrong. The first image was done with tinypng and was pixelated. The updated one is done with photoshop and looks better. I also maintained a small size for the image to load fast on marketplace. The image is still not good enough?

**Comment by NistorCristian** [comment]
This should remain closed. I will submit again as a branch based request instead of master.

**Pull request closed without merging**
