### PR TITLE
Hondo

### PR DESCRIPTION
**Pull request by javierencalada**
Please fill out this checklist to submit your theme to the Marketplace for review.

## Theme Submission checklist

- [x] Pull Request title is title of theme (and nothing else)
- [x] Code changes are a [properly formatted submission](https://github.com/TryGhost/Marketplace/blob/master/.github/CONTRIBUTING.md)
- [x] Theme passes [GScan](https://gscan.ghost.org/)

- [x] I have read about [how the marketplace works](https://github.com/TryGhost/Marketplace/blob/master/README.md) and I completely understand that not all themes are accepted.

### CODE REVIEW

**Comment by JohnONolan** [comment]
This is not following the screenshot guidelines

**Comment by javierencalada** [comment]
@JohnONolan sorry! totally my fault.

Now i uploaded the optimized thumb acording to the guidelines #101 

Thank you!

**Comment by vasanthdeveloper** [comment]
But still, your theme did not get accepted. :(

**Comment by javierencalada** [comment]
Nope... hope it get accepted got a lot of rejected pull requests haha

**Pull request closed without merging**
