### PR TITLE
Add a link to a PR + few typo fix

### PR DESCRIPTION
**Pull request by pascalandy**
Cheers!

### CODE REVIEW

**Comment by JohnONolan** [comment]
You've changed 1 typo and added a bunch of style changes and new typos + linked to commit reference, not a PR. So I'm afraid this isn't at all correct

**Comment by pascalandy** [comment]
I did this PR for this:

screen shot 2017-11-15 at 10 38 17 pm

Feel free to keep the link broken.

**Comment by JohnONolan** [comment]
The link you submitted was wrong. So merging it would have left it still broken.

**Comment by pascalandy** [comment]
It's working here :-p

screen shot 2017-11-15 at 11 05 41 pm

**Pull request closed without merging**
