### PR TITLE
Poveglia

### PR DESCRIPTION
**Pull request by NistorCristian**
## Theme Submission checklist

- [x] Pull Request title is title of theme (and nothing else)
- [x] Code changes are a [properly formatted submission](https://github.com/TryGhost/Marketplace/blob/master/.github/CONTRIBUTING.md)
- [x] Theme passes [GScan](https://gscan.ghost.org/)

- [x] I have read about [how the marketplace works](https://github.com/TryGhost/Marketplace/blob/master/README.md) and I completely understand that not all themes are accepted.

### CODE REVIEW

**Comment by JohnONolan** [comment]
Looks really nice, but can we hit that "load more posts" before taking the screenshot? :)

**Comment by NistorCristian** [comment]
Done 😃

**Comment by JohnONolan** [comment]
Beautiful! Now what about Gonjiam and Okiku?? ;)

**Comment by NistorCristian** [comment]
Thanks. 

I like to be in top 9 items as much as I can. Since I don't have a Featured theme in there I like to add one every 1-2 months. One day I will create a theme that will blow you away ... but that day hasn't come yet. 😊

<details>
  <summary></summary>
  ʏᴇᴛ
</details>

**Comment by JohnONolan** [comment]
Smart! 

We're going to build a new version of Ghost.org soon w/ a new marketplace -- I'll make sure you get beta access so you can give us some feedback about how the ranking and sorting works :)

**Pull request merged**
