### PR TITLE
Dandelion

### PR DESCRIPTION
**Pull request by ericalli**
Please fill out this checklist to submit your theme to the Marketplace for review.

## Theme Submission checklist

- [x] Pull Request title is title of theme (and nothing else)
- [x] Code changes are a [properly formatted submission](https://github.com/TryGhost/Marketplace/blob/master/.github/CONTRIBUTING.md)
- [x] Theme passes [GScan](https://gscan.ghost.org/)

- [x] I have read about [how the marketplace works](https://github.com/TryGhost/Marketplace/blob/master/README.md) and I completely understand that not all themes are accepted.

### CODE REVIEW

**Comment by JohnONolan** [comment]
Looks good - but please review submission guide for how to submit a properly formatted screenshot: https://github.com/TryGhost/Marketplace/blob/master/.github/CONTRIBUTING.md

**Comment by ericalli** [comment]
Thanks John. I'm certain I followed the guidelines -- could you let me know which step I am missing?

**Comment by JohnONolan** [comment]
The submitted image is 338px wide and has an additional white border on the left side - https://raw.githubusercontent.com/TryGhost/Marketplace/b1c6e4d612cabc4253a6a244071f72a1630fb8a2/assets/img/themes/dandelion.jpg

Please have a look at the link above for correct dimensions and process :)

**Comment by ericalli** [comment]
I've updated the screenshot. Thanks!

**Comment by JohnONolan** [comment]
Great, thank you!

**Pull request merged**
