### PR TITLE
Tawau and Hoia

### PR DESCRIPTION
**Pull request by NistorCristian**
In this pull request I'm trying to add two themes. They are called Tawau and Hoia. Just to avoit creating multiple pull requests.

Please fill out this checklist to submit your theme to the Marketplace for review.

## Theme Submission checklist

- [*] Pull Request title is title of theme (and nothing else)
- [*] Code changes are a [properly formatted submission](https://github.com/TryGhost/Marketplace/blob/master/.github/CONTRIBUTING.md)
- [*] Theme passes [GScan](https://gscan.ghost.org/)

- [*] I have read about [how the marketplace works](https://github.com/TryGhost/Marketplace/blob/master/README.md) and I completely understand that not all themes are accepted.

### CODE REVIEW

**Comment by JohnONolan** [comment]
Avoiding creating multiple pull requests = avoiding the very specific submission guidelines = your themes are not going to get reviewed

**Comment by NistorCristian** [comment]
Hi John. Unfortunately, I made a mistake and deleted the old fork. Don't know why I thought that I have to make a pull request for each theme individually. Is there a way for me to solve this problem ? I guess I shoud've updated the fork if I wanted multiple themes, right? I'm sorry for all this trouble.

**Comment by NistorCristian** [comment]
Yup. I'm an idiot. I can't recover the old fork. Can we keep this as the main PR for my account since I can't recover the old fork? I'm very sorry.

**Comment by JohnONolan** [comment]
You do have to make a pull request for each theme individually - that's exactly the point

**Comment by NistorCristian** [comment]
I apologize for my mistake. I will do them separately. Thank you for your answer and sorry for all this trouble.

**Pull request closed without merging**
