### PR TITLE
Privado theme added

### PR DESCRIPTION
**Pull request by rupok**
Please fill out this checklist to submit your theme to the Marketplace for review.

## Theme Submission checklist

- [x] Pull Request title is title of theme (and nothing else)
- [x] Code changes are a [properly formatted submission](https://github.com/TryGhost/Marketplace/blob/master/.github/CONTRIBUTING.md)
- [x] Theme passes [GScan](https://gscan.ghost.org/)

- [x] I have read about [how the marketplace works](https://github.com/TryGhost/Marketplace/blob/master/README.md) and I completely understand that not all themes are accepted.

### CODE REVIEW

**Comment by JohnONolan** [comment]
Hi Rupok, unfortunately this design is too similar to Casper 1.0

**Comment by rupok** [comment]
Hi @JohnONolan It's fine if you don't list the theme but how come it's too similar to Casper? It's not even close in design. Also the theme is live from 2015.

**Comment by JohnONolan** [comment]
"Not even close" is quite a stretch. And Casper 1.0 was made in 2014.

image

image

**Comment by rupok** [comment]
I see, you meant the old Casper. Well, can't do much with that above the fold part yet with Ghost but certainly it's customizable with logo/icon etc. And single post is quite different. However your marketplace, you decide. Best of luck.

**Pull request closed without merging**
